### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by AanGrow** [imvast/TokenToOauth#2]
**Error.**
00:48:26 `(!)` **Error** | **{"message": "404: Not Found", "code": 0}**

**Used link:**
 https://discord.com/oauth2/authorize?client_id=1109612424660779078&redirect_uri=https://restorecord.com/api/callback&response_type=code&scope=identify+guilds.join&state=1101944312884903966
 
Any other links not work too idk why
![WindowsTerminal_SgePchwEd0](https://github.com/imvast/TokenToOauth/assets/134654286/8640b9f6-754e-4d13-9b29-f14217a7a525)

**Comment by imvast** [comment]
fixed

**Comment by hackern88** [comment]
> ixed

same issue
