### ISSUE TITLE
Obsfucate link support

### ISSUE THREAD

**Issue by AanGrow** [imvast/TokenToOauth#4]
It is not work with obsfucated links like this:
 - https://discord.com/api/oauth2/authorize?client_id=1105965001648386088&redirect_uri=http%3A%2F%2Fidlewoodrpg.com%3A8085%2Fcallback&response_type=code&scope=identify%20guilds.join&state=%7B%22guild%22%3A%221110701824765345835%22%2C%22bot%22%3A%221105965001648386088%22%7D

It works with normal links but not work with obsfucated.

**Comment by imvast** [comment]
https://discord.com/oauth2/authorize?client_id=1105965001648386088&redirect_uri=http%3A%2F%2Fidlewoodrpg.com%3A8085%2Fcallback&response_type=code&scope=identify%20guilds.join&state=%7B%22guild%22%3A%221110701824765345835%22%2C%22bot%22%3A%221105965001648386088%22%7D

**Comment by imvast** [comment]
`self.uri = self.uri.replace("api/oauth2", "oauth2")`
